# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Unit-Tests:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e "code/python/.[testing]"
    - name: Install Node dependencies
      run: |
        cd code/nodejs/
        npm ci 
        npm i -g jest
        cd ../../../
    - name: Test with Pytest
      run: |
        cd code/python/
        pytest . 
        cd ../../
    - name: Docker DynamoDB
      uses: rrainn/dynamodb-action@v2.0.0
      with:
        port: 8000
        cors: '*'
    - name: Test with Jest
      run: |
        cd code/nodejs/
        npm test
  Terraform:
    runs-on: ubuntu-18.04
    needs: Unit-Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Lambda Layers
        run: |
          cd setup/
          bash setup.sh